### ISSUE TITLE
Support for Webpack 3

### ISSUE THREAD

**Issue by alexilyaev** [JaKXz/stylelint-webpack-plugin#101]
Updated to Webpack 3 and got this:

```
warning "stylelint-webpack-plugin@0.7.0" has incorrect peer dependency "webpack@^2 || ^2.2.0-rc.0 || ^2.1.0-beta.0 || ^1.13.2".
```

**Comment by JaKXz** [comment]
@alexilyaev thanks for pointing this out, I need to publish a patch. Will try to do so tonight!

**Comment by JaKXz** [comment]
`+ stylelint-webpack-plugin@0.7.1` published! 👍
