### ISSUE TITLE
Ignoring files, using .stylelintignore doesn't seem to work, alternative ?

### ISSUE THREAD

**Issue by appsolutegeek** [JaKXz/stylelint-webpack-plugin#105]
Hi,

I have passed in a glob to my files config on stylelint webpack plugin like so

`    new StyleLintPlugin({emitErrors: false, files: ['**/*.+(css|scss)']})`

I also have a number of CSS files from 3rd parties that I have placed under my assets/css/external directory, and I added a .stylelintignore file in the /external direcory with the following contents

        **/*.css

but also tried

       **/*.*

But it doesn't seem to respect it, the webpack process shows all the warning still in the console for the files I wish to ignore.

Any ideas? Am I doing something wrong?

Thanks

**Comment by JaKXz** [comment]
@appsolutegeek sorry for the delayed reply, you could add a negated glob for the `assets/css/external` folder so that it's not included.

`.stylelintignore` is a responsibility of stylelint as far as I'm aware, so have you been able to reproduce it with just the stylelint CLI?

**Comment by JaKXz** [comment]
I'm going to close this issue for now due to inactivity. I hope your problem was resolved @appsolutegeek :) but feel free to let me know if not and we can reopen this.
