### ISSUE TITLE
Wrong Stylelint version, not respecting peer dependency (using Yarn)

### ISSUE THREAD

**Issue by alexilyaev** [JaKXz/stylelint-webpack-plugin#106]
This might be a Yarn issue...

In `package.json`:

```
"stylelint": "7.12.0",
"stylelint-webpack-plugin": "0.8.0",
```

## Installing using Yarn v0.27.5

Running `npm ls stylelint`:

```
├── stylelint@7.12.0 
└─┬ stylelint-webpack-plugin@0.8.0
  └── stylelint@7.11.0 
```

Error:

```js
Error: Undefined rule selector-max-id
    at module.exports (/Users/alex/www/Node/Personal/dynamo-builder/node_modules/stylelint-webpack-plugin/node_modules/stylelint/lib/utils/configurationError.js:8:27)
    at Object.keys.forEach.ruleName (/Users/alex/www/Node/Personal/dynamo-builder/node_modules/stylelint-webpack-plugin/node_modules/stylelint/lib/augmentConfig.js:279:13)
    at Array.forEach (native)
    at normalizeAllRuleSettings (/Users/alex/www/Node/Personal/dynamo-builder/node_modules/stylelint-webpack-plugin/node_modules/stylelint/lib/augmentConfig.js:275:29)
    at augmentConfigBasic.then.then.then.then.augmentedConfig (/Users/alex/www/Node/Personal/dynamo-builder/node_modules/stylelint-webpack-plugin/node_modules/stylelint/lib/augmentConfig.js:84:12)
```

`selector-max-id` was added only in `7.12.0`.  
I'd expect `stylelint-webpack-plugin` to use the peer instead of installing it's own version of Stylelint.

## Installing using npm v5.0.3

**Works as expected**.

Running `npm ls stylelint`:

```
├── stylelint@7.12.0 
└─┬ stylelint-webpack-plugin@0.8.0
  └── stylelint@7.12.0  deduped
```

**Comment by alexilyaev** [comment]
For now updated in `yarn.lock` the `7.11.0` version to `7.12.0` and ran `yarn --force` and it worked:

```
$ yarn list stylelint
yarn list v0.27.5
└─ stylelint@7.12.0
```

**Comment by JaKXz** [comment]
Sounds like a `yarn` issue, though now that I think about it, since stylelint is a direct dependency of this package, it doesn't necessarily need to be listed in peerDeps. I'd welcome a PR to change this, but I'm okay with the status quo. That probably won't help with this issue directly, but it would be a good cleanup item.

**Comment by alexilyaev** [comment]
I agree it's a Yarn issue.

But, Ideally, I think it would be a peer dep only.  
Otherwise we will inevitably run into a misconfiguration at some version bump that our `^` version does not match compared to what the user installed.

So, it would be best if we just use what what the user installed.

I'm developing [stylelint-find-rules](https://github.com/alexilyaev/stylelint-find-rules), and I used peerDependencies, works well.

**Comment by JaKXz** [comment]
@alexilyaev if you could try v0.9.0, it should solve your problem [while upgrading to stylelint v8]. Feel free to close this issue or we can continue the discussion if things aren't working for you.

**Comment by reeddunkle** [comment]
Since stylint v8 is a breaking, major version update, would you consider changing v0.9.0 to a major, breaking version update also?

In our package.json, we have `"stylelint-webpack-plugin": "^0.7.0"`. It took me a while to trace the breaking change back to here.

**Comment by nickgcattaneo** [comment]
@reeddunkle when no major is specified, npm shifts the logic right, so minor becomes major and thus as you noted the caret shouldn't upgrade you to 0.9.0 as you noted in your update. That being said, if the versioning was 1.9.0 and you specified a caret in front of 1.7.1, that would pull in 1.9.0.

**Comment by reeddunkle** [comment]
@nickgcattaneo I didn't know that. Thanks!

**Comment by JaKXz** [comment]
@reeddunkle that's a fair question, I had the same one about [semver](http://semver.org/) :) thanks @nickgcattaneo for chiming in. I'm going to close this for now and a new discussion can start if required in a new issue.
