### ISSUE TITLE
Stylelint 8.0.0

### ISSUE THREAD

**Issue by zslabs** [JaKXz/stylelint-webpack-plugin#110]
Hi,
Thanks so much for making this! I'm currently testing out moving over from `less-hint` to stylelint; since the new `8.0.0` version supports `.less` a bit better through PostCSS. I don't believe I'm running into any issues so far, but are there specific things I can help test to ensure full coverage and potentially bump what's specified in the `package.json`?

**Comment by EthanRutherford** [comment]
https://github.com/JaKXz/stylelint-webpack-plugin/pull/109
