### ISSUE TITLE
getting Cannot find module 'glob'

### ISSUE THREAD

**Issue by DanielRuf** [JaKXz/stylelint-webpack-plugin#121]
<details>
<summary>error message</summary>
module.js:515
    throw err;
    ^

Error: Cannot find module 'glob'
    at Function.Module._resolveFilename (module.js:513:15)
    at Function.Module._load (module.js:463:25)
    at Module.require (module.js:556:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (..\node_modules\globby\index.js:5:12)
    at Module._compile (module.js:612:30)
    at Object.Module._extensions..js (module.js:623:10)
    at Module.load (module.js:531:32)
    at tryModuleLoad (module.js:494:12)
    at Function.Module._load (module.js:486:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! material-framework@1.0.0 production: `webpack -p --config webpack.prod.js`
npm ERR! Exit status 1
npm ERR!
</details>

**Comment by JaKXz** [comment]
@DanielRuf can you provide more information about this error? Have you tried reinstalling node modules, or updating npm/yarn?

**Comment by DanielRuf** [comment]
Why did you close the issue? It is not yet resolved.

> Have you tried reinstalling node modules, or updating npm/yarn?

No. This was the latest version at this time. npm is 5.3.0

Some people suggest installing glob locally or globally.

**Comment by DanielRuf** [comment]
See https://github.com/tomscholz/material/commit/c2a40c74acbd89389a76c12395d6674ebe419f16

**Comment by JaKXz** [comment]
Thank you for your response. I closed the issue because with what's given it doesn't seem like it is related to this plugin.

Are you able to reproduce this issue in a clean repo? Are you seeing this issue with glob in other projects?

**Comment by DanielRuf** [comment]
It happened only with the mentioned repository. I did not use or try the plugin with other projects. Replaced it now with an eslint command using a npm script.

It should be reproducible with the linked commit. But I can try it again tomorrow.

**Comment by DanielRuf** [comment]
Well, you labeled it with `needs more info` and closed it and closing means for me this issue isn't relevant anymore
