### ISSUE TITLE
How to look for multi folder/How to look for more than one folder in context 

### ISSUE THREAD

**Issue by ankitdadhich** [JaKXz/stylelint-webpack-plugin#123]
This is how am using the plugin.
But the problem is, How can I target multiple path.

Right now it just looks into `src` folder of same parent.

In my case, I have to look for `src` folder in same parent plus a folder outside the parent folder.

Is it possible??

>    new StyleLintPlugin({
            context: "multiple path possible?",
            configFile: '.stylelintrc',
            files: '**/*.scss',
            failOnError: false,
            quiet: false,
            syntax: 'scss'
        }),

**Comment by JaKXz** [comment]
The `files` option takes an array of globs, [as documented](https://github.com/JaKXz/stylelint-webpack-plugin#options).

**Comment by ankitdadhich** [comment]
new StyleLintPlugin({
             context: pathToGrandParentFolder,
             files: ['pathToParentFolder/*.scss', 'pathToUncleFolder/*.scss'],
         }),

Well am doing this and this does not not look for files.
Am doing it in wrong way?
