### ISSUE TITLE
scss not processed

### ISSUE THREAD

**Issue by ibdf** [JaKXz/stylelint-webpack-plugin#127]
I switched from the _stylelint-processor-html_ plugin, where everything worked fine, except for the error line numbers. But after switching the processor settings my *.scss files are no longer processed, only the scss styles found in my .vue files.
style.

I understand that by default this plugin looks for <style>, but does it not process *.scss files? Or is this a setting I need to pass? I've been reading the docs for stylelint and for this plugin, but I seem to be missing something obvious.

My stylelint.config.js

```javascript
module.exports = {
  plugins: ["stylelint-order"],
  processors: ["@mapbox/stylelint-processor-arbitrary-tags"],
  extends: ["stylelint-config-standard"],
  rules: {
    "no-empty-source": null,
    "order/properties-alphabetical-order": true,
    "selector-pseudo-element-colon-notation": "single",
    "no-descending-specificity": null,
    "at-rule-no-unknown": [
      true,
      {
        ignoreAtRules: ["function", "if", "mixins", "include"]
      }
    ]
  }
};
```

And my webpack config:

```javascript
new StylelintPlugin({
      files: ['**/*.vue', '**/*.scss'],
      emitErrors: false,
}),
```

Thanks.

**Comment by JaKXz** [comment]
I think you need to set the `syntax: 'scss'` option in your webpack config.

**Comment by JaKXz** [comment]
@ibdf any updates on this? I hope things worked out for you.

**Comment by ibdf** [comment]
@JaKXz I had an issue, where the autofix option ended up deleting all the code on a file, so for now I stopped using any css style lint until I have the time to go through it again. So you can close this as I honestly have no time to work on it right now.
