### ISSUE TITLE
Lint dirty files only

### ISSUE THREAD

**Issue by athyuttamre** [JaKXz/stylelint-webpack-plugin#30]
When trying to introduce stylelint to an existing codebase, it can be very hard if the webpack console blows up with errors from across the codebase.

It would be great to have an option `lintDirtyModulesOnly: true`, that would:
- Skip linting files the first time it encounters them (to avoid linting during Webpack's first run)
- Only lint edited files during incremental builds

At a high level, this could be achieved if the plugin stores a stateful map between module names and the number of times it has processed them. If the number of times is greater than 1, and Webpack has processed the file (i.e. it has changed), then we can lint it.

**Comment by JaKXz** [comment]
Thanks for the suggestion @athyuttamre - want to take a crack at a PR? :)

**Comment by JaKXz** [comment]
Thanks to @sergesemashko this has been published in `+ stylelint-webpack-plugin@0.6.0` :) please give it a shot, hopefully it helps!
