### ISSUE TITLE
Support postcss-report

### ISSUE THREAD

**Issue by Itrulia** [JaKXz/stylelint-webpack-plugin#44]
I'd like to use https://github.com/postcss/postcss-reporter with this plugin, is there a way already?

**Comment by JaKXz** [comment]
I believe you can just [pull out the formatter function](https://github.com/postcss/postcss-reporter#standalone-formatter) and [pass it as a prop to the `StyleLintPlugin` options](https://github.com/JaKXz/stylelint-webpack-plugin#options). 

Let me know if that works for you, and if it does, feel free to make a PR documenting the example :smiley:

**Comment by JaKXz** [comment]
@Itrulia I'm going to close this for now since I believe it is supported. Feel free to ping if not or if you need more help.

**Comment by Itrulia** [comment]
Oh hey, sorry for not answering. Afaik it isnt (tried  it) but with webpack 2 I can use postcss directly with different configs, so if you need that formatter you can switch to only use postcss.
