### ISSUE TITLE
Performance optimization suggestion, lint only failed files + changed files

### ISSUE THREAD

**Issue by sergesemashko** [JaKXz/stylelint-webpack-plugin#54]
On my current project introducing stylelint raised watch build time from ~3s to ~25s. I guess, it happened because of big amount of files and amount of rules.

So, maybe we could cache files that failed to lint on initial run and then include them + files that changed for linting. That should decrease overhead from linting all the files that passed initially and hasn't been changed. 

It seems this will require slight update how to deal with stylelint formatter, because in order to get failed files it would require both JSON and string output. 

If this suggestion sounds good, I'd be happy to poke around and apply the optimization.

**Comment by JaKXz** [comment]
@sergesemashko this was implemented with `lintDirtyModulesOnly` right?

**Comment by sergesemashko** [comment]
@JaKXz, correct. 
BTW, `cache` option [was added](https://github.com/stylelint/stylelint/pull/2293) to stylelint. So, if someone has performance issues, that flag can dramatically decrease lint time.
