### ISSUE TITLE
Version upgrade from 0.3.1 to 0.5.1 broke other the functionality of react-select2-wrapper

### ISSUE THREAD

**Issue by apurvajain** [JaKXz/stylelint-webpack-plugin#63]
As soon as I upgraded the version of `stylelint-webpack-plugin` from 0.3.1 to 0.5.1 the react-select2-wrapper stopped working. Anyone else facing similar issue ? Please help

**Comment by JaKXz** [comment]
Sorry I'm not sure how this plugin affected your build. Would you mind sharing more information that would help reproduce the issue, or point us to your repo or a minimal reproduction?
