### ISSUE TITLE
Feature request: warnings rather than errors

### ISSUE THREAD

**Issue by Vinnl** [JaKXz/stylelint-webpack-plugin#65]
Currently, when using Webpack Dev Server with hot reloading, not adhering to my stylelist rules results in an error. The dev server then thinks compilation has failed and will not serve the updated styles.

I want to adhere to my linting rules, but perhaps not as strictly when I'm just messing about locally :) Thus, an option like ts-loader's [`emitErrors`](https://www.npmjs.com/package/tslint-loader) would be nice, that can set stylelint errors to be emitted as warnings.

**Comment by Vinnl** [comment]
I went ahead and created a PR for this: #66. Let me know if that looks OK :)

**Comment by mhlavacka** [comment]
👍

**Comment by Zephir77167** [comment]
Hi, very nice feature, I am looking forward to it! :+1:

**Comment by JaKXz** [comment]
Thanks @Vinnl for getting the work in on this :) 

@mhlavacka @Zephir77167 and others, if you could try installing `stylelint-webpack-plugin#master` and kicking the tires that would be great! I'll be releasing a new version soon.

**Comment by Vinnl** [comment]
For those who also never installed an NPM package directly from a repo before, you can simply run `npm install JaKXz/stylelint-webpack-plugin#master`.

It appears to work fine for me. I did encounter a strange thing that I reported in the PR #66, but I suppose that's probably a new issue?
