### ISSUE TITLE
No stylelintrc file error when using the package file stylelint property

### ISSUE THREAD

**Issue by nelsyeung** [JaKXz/stylelint-webpack-plugin#67]
I'm getting this error
```
Error: ENOENT: no such file or directory, open '/Users/nelsyeung/Sites/es6-web-template/.stylelintrc'
```
even though I have the following in my `package.json`
```json
"stylelint": {
  "extends": "stylelint-config-standard"
},
```

**Replication details:**
```sh
git clone https://github.com/nelsyeung/es6-web-template.git
cd es6-web-template
git checkout dev
npm i
npm start
```

**Notes**
OS: macOS Sierra
Webpack: 2.2.1
stylelint-webpack-plugin: 0.5.1

Stylelint (the cli tool) runs fine with settings inside `package.json`, which you can also play around with inside my repository above.

**Comment by JaKXz** [comment]
`+ stylelint-webpack-plugin@0.6.0` was just published, please [remove the `configFile` option if you have it] give it a shot :)

**Comment by karlhorky** [comment]
Works for me in the demo repo provided above, thanks @JaKXz!

**Comment by JaKXz** [comment]
Thanks for the ping @karlhorky! I should have release a patch version right away but v0.6.0 is also good 😄

**Comment by nelsyeung** [comment]
v0.6.0 looks good. 👍  Thanks!

**Comment by karlhorky** [comment]
No problem, glad to help!
