### ISSUE TITLE
emitError: false emits empty warning

### ISSUE THREAD

**Issue by nijk** [JaKXz/stylelint-webpack-plugin#69]
Using latest code, if I set the config `emitErrors: false` then I see the webpack build passes but with a warning. This appears to be [due to line 22 of run-compilation.js](https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/lib/run-compilation.js#L22-L28) where the result from the ternary should be `[]` rather than `results`

![screen shot 2017-02-22 at 15 03 36](https://cloud.githubusercontent.com/assets/1615460/23217166/40a17b4c-f910-11e6-8a68-0f4e3cdb9de1.png)

**Comment by JaKXz** [comment]
Thanks for pointing this out @nijk, it's a great find. I took a quick look at your PR, but I think I have a better solution with `ramda` that also addresses some tech debt I have been wanting to fix for a while. Let me know what you think of #71 :)
