### ISSUE TITLE
No correct error message in console

### ISSUE THREAD

**Issue by Mari4ka89** [JaKXz/stylelint-webpack-plugin#78]
Hello,

In version 0.7.0 I have such error message in console:
Error: Failed because of a stylelint error. 
at linterSuccess (.../node_modules/stylelint-webpack-plugin/lib/run-compilation.js:35:14)

but in version 0.5.0 were clear error messages:
13:7  ✖  Expected indentation of 8 spaces   indentation

Could you please take a look on it?

**Comment by JaKXz** [comment]
@Mari4ka89 sorry for the delayed response, but I haven't had much time for OSS lately. 

Feel free to submit a PR, even with just failing tests so that we have somewhere to start :) I'd be happy to help others contribute!

**Comment by mahmood-sajjadi** [comment]
I had the same issue,
documentation should be updated, the code can be improved too

based on 
https://github.com/JaKXz/stylelint-webpack-plugin/blob/master/lib/run-compilation.js#L30:L32

`quiet` parameter is mandatory to be false
`formatter` parameter should be defined

so result will be something like this:
new StyleLintPlugin({
        configFile: root('.stylelintrc'),
        formatter: require('stylelint-formatter-pretty'),
        emitErrors: true,
        failOnError: true,
        quiet: false,
        syntax: 'scss'
}),

**Comment by JaKXz** [comment]
So, the `quiet` option has been removed as of v0.10.2, since it was just redundant. I'm going to close this issue for now, but please feel free to reopen or make a new issue if you are still seeing it on v0.10.3+
