### ISSUE TITLE
A way to lint a package in node_modules?

### ISSUE THREAD

**Issue by Zephir77167** [JaKXz/stylelint-webpack-plugin#98]
Hi,

I have a local node package in my dependencies, and would expect stylelnt-webpack-plugin to lint those files as they are directly imported by my JS files.

Is there a way to do so?

Thanks in advance,

**Comment by JaKXz** [comment]
You could try specifying another glob to the `files` array:

```
files: [
  'node_modules/package/styles/**/*.css',
  'your/css/files/**/*.css'
]
```

But I can't guarantee that will work. Give it a shot and let me know. I don't think that this is a totally unreasonable request if you explicitly specify that you want to lint something in the node_modules folder. I would support a PR for this if my suggestion doesn't work, but unfortunately I don't have the cycles to make one right now.

**Comment by Zephir77167** [comment]
That didn't work, but I found a workaround by adding `../package/**/*.css` in `files`. Indeed, my package is a node dependency served via linklocal.

Thanks for your help!

**Comment by JaKXz** [comment]
Interesting. Thanks for pointing this out! I have a feeling that stylelint itself ignores files in the node_modules directory. Going to close this now.
